'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const html = fs.readFileSync(path.join(root, 'studio', 'index.html'), 'utf8');
const source = fs.readFileSync(path.join(root, 'studio', 'assets', 's3-animate-ui.js'), 'utf8');
assert.match(html, /assets\/s3-animate-ui\.js\?v=20260812-s3-animate-execution-r2/);
assert.match(source, /\/api\/canvas\/provider-status/);
assert.match(source, /\/api\/projects\/.*\/assets/);
assert.match(source, /\/api\/projects\/.*\/canvas\/jobs/);
assert.match(source, /\/dry-run/);
assert.match(source, /skillKey:'runninghub-animate-motion-transfer'/);
assert.match(source, /image_asset/);
assert.match(source, /motion_video/);
assert.match(source, /durationSeconds/);
assert.match(source, /video.*controls/);
assert.match(source, /reconcile_task/);
assert.match(source, /\/authorize/);
assert.match(source, /confirmProviderSpend:true/);
assert.match(source, /window\.confirm/);
console.log(JSON.stringify({ok:true,verified:['Studio loads the S3 Animate control surface','the node binds one current-project image and one current-project video','the candidate persists duration, ratio, ports, recovery actions and task reference','dry-run remains free of provider submission','a separate confirmed action submits once and completed jobs expose a playable project video preview']}));
