'use strict';
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const {spawn} = require('node:child_process');
const {chromium} = require('playwright');
const root = __dirname;
const pause = milliseconds => new Promise(resolve => setTimeout(resolve, milliseconds));
async function waitForHealth(baseUrl) { for (let attempt = 0; attempt < 100; attempt += 1) { try { if ((await fetch(baseUrl + '/api/health')).ok) return; } catch {} await pause(100); } throw new Error('s2_ui_server_not_ready'); }
async function main() {
  const dataRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'niannian-s2-ui-')); const port = 29100 + crypto.randomInt(400); const baseUrl = 'http://127.0.0.1:' + port; const token = crypto.randomBytes(18).toString('hex'); const user = {id:'USR-S2-UI',email:'s2-ui@example.test',status:'active'}; const project = {id:'NN-S2-UI',ownerId:user.id,name:'S2 UI',projectKind:'redraw',canvasOnly:true,status:'ready',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),runtime:{}}; const tokenHash = crypto.createHash('sha256').update(token).digest('hex');
  await Promise.all([fs.writeFile(path.join(dataRoot, 'users.json'), JSON.stringify([user])),fs.writeFile(path.join(dataRoot, 'sessions.json'), JSON.stringify([{tokenHash,userId:user.id,expiresAt:new Date(Date.now() + 3600000).toISOString()}])),fs.writeFile(path.join(dataRoot, 'projects.json'), JSON.stringify([project])),fs.writeFile(path.join(dataRoot, 'canvas-projects.json'), JSON.stringify([project])),fs.writeFile(path.join(dataRoot, 'canvas-documents.json'), '{}'),fs.writeFile(path.join(dataRoot, 'canvas-assets.json'), '[]'),fs.writeFile(path.join(dataRoot, 'canvas-generation-jobs.json'), '[]'),fs.writeFile(path.join(dataRoot, 'script-projects.json'), '[]'),fs.writeFile(path.join(dataRoot, 'workspace-bindings.json'), '[]')]);
  const server = spawn(process.execPath, ['server.js'], {cwd:root,env:{...process.env,PORT:String(port),DATA_DIR:dataRoot,YUNFEI_IMAGE2_1K_API_KEY:'test-only-key',NIANNIAN_CANVAS_YUNFEI_1K_SUBMIT:'on',NIANNIAN_RUNNINGHUB_SUBMIT:'off'},stdio:['ignore','ignore','ignore']}); let browser;
  try {
    await waitForHealth(baseUrl); const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLkrQAAAABJRU5ErkJggg==', 'base64'); const form = new FormData(); form.append('kind', 'reference_image'); form.append('asset', new Blob([png], {type:'image/png'}), 'reference.png'); const upload = await fetch(baseUrl + '/api/projects/' + project.id + '/assets', {method:'POST',headers:{cookie:'niannian_session=' + token,'x-niannian-project-kind':'redraw'},body:form}); assert.equal(upload.status, 201);
    browser = await chromium.launch({headless:true}); const context = await browser.newContext({viewport:{width:1440,height:900}}); await context.addCookies([{name:'niannian_session',value:token,url:baseUrl}]); const page = await context.newPage(); const failures = []; page.on('pageerror', error => failures.push(error.message)); await page.goto(baseUrl + '/studio/?projectId=' + project.id + '&projectKind=redraw#/studio', {waitUntil:'networkidle'}); await page.getByRole('button', {name:'打开关键帧图像候选'}).click(); const panel = page.locator('#s2-image2-panel'); await panel.waitFor({state:'visible'}); await panel.getByRole('radio', {name:/reference\.png/}).check(); await panel.getByLabel('画面说明').fill('保留角色轮廓的关键帧构图'); assert.equal(await panel.locator('[data-s2-resolution]').inputValue(), '1k'); await panel.getByRole('button', {name:'建立生成候选'}).click(); try { await panel.getByText(/候选已保存/).waitFor({timeout:5000}); } catch (error) { throw new Error('S2 candidate failed: ' + await panel.innerText() + ' | ' + failures.join(' | ')); } await panel.getByText(/1024x1024/).first().waitFor(); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    await fs.mkdir(path.join(root, 'test-results'), {recursive:true}); await page.screenshot({path:path.join(root, 'test-results', 's2-image2-desktop.png'), fullPage:false}); await page.setViewportSize({width:390,height:844}); await page.reload({waitUntil:'networkidle'}); await page.getByRole('button', {name:'打开关键帧图像候选'}).click(); await page.locator('#s2-image2-panel').waitFor({state:'visible'}); await page.screenshot({path:path.join(root, 'test-results', 's2-image2-mobile.png'), fullPage:false}); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true); assert.deepEqual(failures, []); await context.close(); await browser.close(); browser = null; console.log(JSON.stringify({ok:true,verified:['desktop creates an Image2 candidate from a current-project image','candidate derives the 1K 1024x1024 specification','mobile panel stays within viewport','no provider authorization is sent']}));
  } finally { if (browser) await browser.close(); server.kill(); await fs.rm(dataRoot, {recursive:true,force:true}); }
}
main().catch(error => { console.error(error.stack || error.message || String(error)); process.exitCode = 1; });
