'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const html = fs.readFileSync(path.join(root, 'studio', 'index.html'), 'utf8');
const source = fs.readFileSync(path.join(root, 'studio', 'assets', 's4-smart-cut-ui.js'), 'utf8');
assert.match(html, /assets\/s4-smart-cut-ui\.js\?v=20260812-s4-smart-cut-ui-r1/);
assert.match(source, /\/api\/studio\/projects\//);
assert.match(source, /\/smart-cut\/jobs/);
assert.match(source, /\/dry-run/);
assert.match(source, /kind:'smart_cut'/);
assert.match(source, /sourceVideoAssetId/);
assert.match(source, /captionStyle/);
assert.match(source, /execute:false/);
assert.match(source, /<video class="s4-video" controls/);
assert.match(source, /editorProjectId/);
assert.doesNotMatch(source, /confirmProviderSpend/);
assert.doesNotMatch(source, /\/authorize/);
console.log(JSON.stringify({ok:true,verified:['Studio loads the S4 Smart Cut candidate control surface','a current-project video and editing parameters persist as a smart_cut node','candidate creation uses the server dry-run contract only','the external-editor action stays unavailable until the server reports a ready editor project','completed jobs expose a playable project-library video']}));
